[[redirects]]
  from = "/api/v1/*"
  to = "http://localhost:3010/prod/api/v1/:splat"
  status = 200
  force = true
  headers = {x-api-key = "secret"}

[[plugins]]
  package = "@netlify/plugin-gatsby"
